const commands = { 
            'npm':'gerenciador de pacotes JavaScript',
            'npm access':'Definir nível de acesso em pacotes publicados',
            'npm adduser':'Adicionar uma conta de usuário do registro',
            'npm audit':'Execute uma auditoria de segurança',
            'npm bin':'Exibir pasta bin npm',
            'npm bugs':'Bugs para um pacote em um navegador da web talvez',
            'npm build':'Construir um pacote',
            'npm cache':'Manipula o cache de pacotes',
            'npm ci':'Instalar um projeto com uma ficha limpa',
            'npm completion':'Conclusão de tabulação para npm',
            'npm config':'Gerenciar os arquivos de configuração do npm',
            'npm dedupe':'Reduzir a duplicação',
            'npm deprecate':'Preterir uma versão de um pacote',
            'npm dist-tag': 'Modificar tags de distribuição de pacotes',
            'npm docs':'documentos npm',
            'npm doctor':'Verifique seus ambientes',
            'npm edit':'Editar um pacote instalado',
            'npm explore':'Procurar um pacote instalado',
            'npm fund':'Recuperar informações de financiamento',
            'npm help':'Pesquisar documentação de ajuda do npm',
            'npm help-search': 'Obter ajuda no npm',
            'npm hook':'Gerenciar ganchos de registro',
            'npm init':'Crie um arquivo package.json',
            'npm install':'Instalar um pacote',
            'npm install-ci-test':'Instale um projeto com uma ficha limpa e execute testes',
            'npm install-test':'Instale o(s) pacote(s) e execute os testes',
            'npm link':'Link simbólico de uma pasta de pacote',
            'npm logout':'Sair do registro',
            'npm ls':'Listar pacotes instalados',
            'npm org': 'Gerenciar organizações',
            'npm outdated':'Verifique se há pacotes desatualizados',
            'npm owner':'Gerenciar proprietários de pacotes',
            'npm pack':'Criar um tarball de um pacote',
            'npm ping': 'Ping npm registro',
            'npm prefix':'Prefixo de exibição',
            'npm profile':'Altere as configurações do seu perfil de registro',
            'npm prune':'Remover pacotes estranhos',
            'npm publish':'Publicar um pacote',
            'npm rebuild':'Reconstruir um pacote',
            'npm repo':'Abra a página do repositório de pacotes no navegador',
            'npm restart':'Reinicie um pacote',
            'npm root':'Exibir raiz npm',
            'npm run-script':'Execute scripts de pacotes arbitrários',
            'npm search':'Pesquisar pacotes',
            'npm shrinkwrap':'Bloqueie versões de dependência para publicação',
            'npm star':'Marque seus pacotes favoritos',
            'npm stars':'Ver pacotes marcados como favoritos',
            'npm start':'Iniciar um pacote',
            'npm stop':'Parar um pacote',
            'npm team':'Gerenciar equipes da organização e associações de equipe',
            'npm test':'Testar um pacote',
            'npm token':'Gerencie seus tokens de autenticação',
            'npm uninstall':'Remover um pacote',
            'npm unpublish':'Remover um pacote do registro',
            'npm update':'Atualizar um pacote',
            'npm version':'Bump uma versão do pacote',
            'npm view':'Ver informações do registro',
            'npm whoami':'Exibir nome de usuário npm',
            'npm dist-tag':'Mostrar nome do usúario npm',
}

export {commands};